@startuml Usecase
'styles
skinparam packageStyle rectangle
left to right direction


'ACTORS
Actor Customer as customer
Actor Cook as cook



rectangle "Food Ordering App"{
    ' USECASES
    usecase addItemsToCart
    usecase seeMenu
    usecase placeOrder
    usecase seeOrder
    usecase viewCart
    usecase markOrderComplete
    usecase seeWaitTime
    usecase verifyEmail
    usecase verifyRegisteredEmail
    usecase login

    ' SERVICES
    rectangle "<<Service>>\nCalculateWaitTime" as serviceWaitTime
    rectangle "<<Service>>\nMakePayment" as servicePayment

}

'links
customer--seeMenu
customer--addItemsToCart
customer--placeOrder
customer--seeWaitTime
customer--servicePayment
customer--viewCart


seeWaitTime-->serviceWaitTime:<<extends>>

cook--seeOrder
cook--login
cook--markOrderComplete

login--|>verifyRegisteredEmail:<<includes>>
placeOrder--|>verifyEmail:<<includes>>



@enduml