@startuml comps
left to right direction
skinparam linetype ortho


package "Client Side" {
    RECTANGLE Browser
    RECTANGLE "Mobile App"
}

package "Hosted CDN" {
    RECTANGLE CDN
}

package "Server Side" {
    package "Application Server" {
        package "Controller" {
            RECTANGLE "Flask Controller"
            RECTANGLE OrderController
            RECTANGLE PaymentController
            RECTANGLE CookController
            RECTANGLE UserController
            RECTANGLE AdminController
        }

        package "Model" {
            RECTANGLE Order
            RECTANGLE OrderItem
            RECTANGLE Customer
            RECTANGLE Cook
            RECTANGLE Admin
            RECTANGLE Menu
            RECTANGLE Payment
        }

        package "View" {
            RECTANGLE CustomerView
            RECTANGLE CookView
            RECTANGLE AdminView
        }
    }

    database "Relational DB"

}

Browser <-u- CDN
"Mobile App" <-u- CDN

Browser -[#blue]-> "Flask Controller"
"Mobile App" -[#blue]-> "Flask Controller"

"Flask Controller" -[#red]-> CustomerView
"Flask Controller" -[#red]-> CookView
"Flask Controller" -[#red]-> AdminView
"Flask Controller" -[#red]-> Order
"Flask Controller" -[#red]-> Menu
"Flask Controller" -[#red]-> Customer
"Flask Controller" -[#red]-> Payment

Order --> "Relational DB"
Customer --> "Relational DB"
Menu --> "Relational DB"
Payment --> "Relational DB"
OrderController --> Order
PaymentController --> Payment
UserController --> Customer
AdminController --> Admin
AdminController --> Menu
CookController-->Cook
Order-l-> OrderItem

@enduml