@startuml databaseDesign

entity "Customers" as Customers {
    +int customerID
    --
    name: string
    email: string
    password: string
}

entity "Cooks" as Cooks {
    +int cookID
    --
    name: string
    email: string
    password: string
}

entity "Admins" as Admins {
    +int adminID
    --
    name: string
    email: string
    password: string
}

entity "MenuItems" as MenuItems {
    +int menuID
    --
    itemName: string
    category: string
    price: double
}

entity "Orders" as Orders {
    +int orderID
    --
    orderDate: DateTime
    status: OrderStatus
    customerID: int
    paymentID: int
}

entity "OrderItems" as OrderItems {
    +int orderItemID
    --
    orderID: int
    menuID: int
    quantity: int
    price: double
}

entity "Payments" as Payments {
    +int paymentID
    --
    amount: double
    status: string
}

Customers ||--o{ Orders : places
Orders ||--o{ OrderItems : contains
MenuItems ||--o{ OrderItems : includes
Payments ||--|| Orders : settles
@enduml
