@startuml topLevel
left to right direction

package "Client Side" {
  [Browser]
  [Mobile App]
}

package "hosted CDN" {
  [CDN]
}

package "Server Side" {
  package "Application Server" {
    [Controller]
    [View]
    [Model]
  }
  [Relational DB]
}


[Browser] --> [CDN]
[Mobile App] --> [CDN]
[Browser] --> [View]
[Mobile App] <--[View]
[Controller] --> [View]
[Controller] --> [Model]
[Model] --> [Relational DB]
@enduml
