@startuml DesignUpdate2
!theme mars

left to right direction 
actor Customer
actor Cook
actor Admin

rectangle "Food Ordering App" {

    Customer -- (addItemsToCart)
    Customer -- (seeMenu)
    Customer -- (placeOrder) 
    Customer -- (viewCart)
    Customer -- (seeWaitTime) 
    Customer -- (MakePayment) 
    Customer -- (trackOrder)
    Customer -- (provideFeedback)
    
    Cook -- (login)
    Cook -- (seeOrder)
    Cook -- (markOrderComplete)

    Admin -- (manageMenu)
    Admin -- (manageUsers)
    Admin -- (viewReports)
    
    (placeOrder) --> (verifyEmail) : <<extends>>
    (placeOrder) --> (sendOrderNotification)

    rectangle "<<Service>>\nCalculateWaitTime" as serviceWaitTime
    rectangle "<<Service>>\nMakePayment" as MakePayment

    MakePayment --> (verifyPayment) : <<includes>>
    (MakePayment) --> (handlePaymentFailure) : <<includes>>
    (seeWaitTime) --> (CalculateWaitTime)
    (login) --> (verifyRegisteredEmail) : <<includes>>
}

@enduml
