@startuml Usecase
!theme toy

'styles
skinparam packageStyle rectangle
left to right direction


'ACTORS
Actor Customer as customer
Actor Cook as cook
Actor Admin as admin




rectangle "Food Ordering App"{
    ' USECASES
    usecase addItemsToCart
    usecase seeMenu
    usecase placeOrder
    usecase seeOrder
    usecase viewCart
    usecase markOrderComplete
    usecase seeWaitTime
    usecase verifyEmail
    usecase verifyRegisteredEmail
    usecase login
    usecase trackOrder

    usecase manageUsers
    usecase manageMenu
    usecase viewReports

    ' SERVICES
    rectangle "<<Service>>\nCalculateWaitTime" as serviceWaitTime
    rectangle "<<Service>>\nMakePayment" as servicePayment

}

'links
customer--seeMenu
customer--addItemsToCart
customer--placeOrder
customer--seeWaitTime
customer--servicePayment
customer--viewCart
customer--trackOrder


seeWaitTime-->serviceWaitTime:<<extends>>

cook--seeOrder
cook--login
cook--markOrderComplete

login--|>verifyRegisteredEmail:<<includes>>
placeOrder--|>verifyEmail:<<includes>>

admin--manageMenu
admin--manageUsers
admin--viewReports



@enduml