# Generated by Django 5.1 on 2024-08-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('ER', 'Eatery'), ('DR', ''), ('SD', 'Junior'), ('U', 'Unknow')], default='U', max_length=2)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
