# Generated by Django 5.1 on 2024-08-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T01Menu', '0002_alter_menuitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('ER', 'Eatery'), ('DR', 'Drink'), ('SD', 'Sides'), ('DS', 'Desserts'), ('SL', 'Salads'), ('BV', 'Beverages'), ('U', 'Unknown')], default='U', max_length=2),
        ),
    ]
